
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EShopCoffee.Models.DataLayer
{

using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
 [MetadataType(typeof(Blog_Post_MetaData))]
    public partial class Blog_Post
{

    public int postId { get; set; }

    public int groupId { get; set; }

    public string post_Title { get; set; }

    public string post_ShortDiscription { get; set; }

    public string post_Discription { get; set; }

    public Nullable<int> post_Visit { get; set; }

    public Nullable<System.DateTime> post_datetime { get; set; }

    public string post_Image { get; set; }

    public string post_Video { get; set; }



    public virtual Blog_Group Blog_Group { get; set; }

}

}
