//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopCoffee.Models.DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
     [MetadataType(typeof(OrderDetails_MetaData))]
    public partial class OrderDetails
    {
        public long DetailId { get; set; }
        public long OrderId { get; set; }
        public long ProductID { get; set; }
        public long Price { get; set; }
        public int Count { get; set; }
        public long Discountprice { get; set; }
        public long TotalPrice { get; set; }
        public string ProductImage { get; set; }
        public string ProductTitle { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product_EShop Product_EShop { get; set; }
    }
}
