//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopCoffee.Models.DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
     [MetadataType(typeof(PersntOff_MetaData))]
    public partial class PersntOff
    {
        public long Off_Id { get; set; }
        public long Product_Id { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Persent_Off { get; set; }
        public bool IsExpire { get; set; }
    
        public virtual Product_EShop Product_EShop { get; set; }
    }
}
