//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopCoffee.Models.DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
     [MetadataType(typeof(Product_Comments_MetaData))]
    public partial class Product_Comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Comments()
        {
            this.Product_Comments1 = new HashSet<Product_Comments>();
        }
    
        public long Comment_Id { get; set; }
        public long Product_Id { get; set; }
        public long UserId { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string UserImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Comments> Product_Comments1 { get; set; }
        public virtual Product_Comments Product_Comments2 { get; set; }
        public virtual Product_EShop Product_EShop { get; set; }
        public virtual Users Users { get; set; }
    }
}
