//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopCoffee.Models.DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
     [MetadataType(typeof(Product_EShop_MetaData))]
    public partial class Product_EShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_EShop()
        {
            this.Product_Comments = new HashSet<Product_Comments>();
            this.Product_Galllery = new HashSet<Product_Galllery>();
            this.Product_Proerty_Select = new HashSet<Product_Proerty_Select>();
            this.Product_Select_Groups = new HashSet<Product_Select_Groups>();
            this.Product_Tags = new HashSet<Product_Tags>();
            this.TotalSell = new HashSet<TotalSell>();
            this.PersntOff = new HashSet<PersntOff>();
            this.ShopCard = new HashSet<ShopCard>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public long Product_Id { get; set; }
        public string Proudct_Title { get; set; }
        public long Product_Count { get; set; }
        public bool Product_IsInStock { get; set; }
        public string Product_Discription { get; set; }
        public long Product_Price { get; set; }
        public string Product_ImageName { get; set; }
        public System.DateTime Product_CreateDate { get; set; }
        public bool Product_Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Comments> Product_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Galllery> Product_Galllery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Proerty_Select> Product_Proerty_Select { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Select_Groups> Product_Select_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Tags> Product_Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalSell> TotalSell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersntOff> PersntOff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCard> ShopCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
