
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EShopCoffee.Models.DataLayer
{

using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
 [MetadataType(typeof(Product_Galllery_MetaData))]
    public partial class Product_Galllery
{

    public long Gallery_Id { get; set; }

    public long Product_Id { get; set; }

    public string Gallery_Image_Title { get; set; }

    public string Gallery_Image_Name { get; set; }



    public virtual Product_EShop Product_EShop { get; set; }

}

}
