
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EShopCoffee.Models.DataLayer
{

using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
 [MetadataType(typeof(Users_MetaData))]
    public partial class Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Users()
    {

        this.Product_Comments = new HashSet<Product_Comments>();

        this.Order = new HashSet<Order>();

    }


    public long User_Id { get; set; }

    public long User_Role_Id { get; set; }

    public string User_Name { get; set; }

    public string User_Email { get; set; }

    public string User_Phone { get; set; }

    public string User_Password { get; set; }

    public string User_Active_Code { get; set; }

    public bool User_IsActive { get; set; }

    public System.DateTime User_RegisterDate { get; set; }

    public string User_Image { get; set; }

    public string User_Address { get; set; }

    public string User_Postal_Code { get; set; }

    public string User_State_Name { get; set; }

    public string User_City_Name { get; set; }

    public Nullable<int> User_State_ID { get; set; }

    public Nullable<int> User_City_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product_Comments> Product_Comments { get; set; }

    public virtual Roles Roles { get; set; }

    public virtual tblOstan tblOstan { get; set; }

    public virtual tblShahrestan tblShahrestan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Order { get; set; }

}

}
